title: Aman Kumar # your name (or website title) here
logo: "/images/09 copy.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a love of helping others and problem-solving. 
  My strong communication skills along with my technical skills in Statistics, SQL, Excel, Power BI, 
  Python, Flask, HTML, EDA, Machine Learning, Deep Learning, Yolo, NLP, BERT, ChatGPT, Hugging Face, LLMs, Prompt Engineering, and Lang chain 
  allow me to transform data into impactful insights that lead to the best business decisions. 
  
  <br><br>
  <a href="https://www.linkedin.com/in/amankumarchahar//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
